using Day_8;

namespace Tests;

[TestClass]
public class Day_8_Tests
{
    [TestMethod]
    public void Test_Day_7_Part_One()
    {
        var input = """
                    ............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............
                    """;
        var result = Solver.Run_PartOne(input);
        var expected = 14;
        
        Assert.AreEqual(expected, result);
    }
    [TestMethod]
    public void Test_Day_7_Part_Two()
    {
        var input = """
                    ............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............
                    """;
        var result = Solver.Run_PartTwo(input);
        var expected = 34;
        
        Assert.AreEqual(expected, result);
    }
}